from __future__ import annotations

import pytest
from pydantic import ValidationError

from skill_pipeline.pipeline_models.prompt import (
    PromptChunkWindow,
    PromptPacketArtifact,
    PromptPacketManifest,
)


class TestPromptChunkWindow:
    def test_valid_single_pass_window(self) -> None:
        window = PromptChunkWindow(
            window_id="w0",
            chunk_index=0,
            chunk_count=1,
            target_block_ids=["B001", "B002"],
            estimated_tokens=1200,
        )
        assert window.window_id == "w0"
        assert window.chunk_index == 0
        assert window.chunk_count == 1
        assert window.overlap_block_ids == []

    def test_valid_chunked_window_with_overlap(self) -> None:
        window = PromptChunkWindow(
            window_id="w1",
            chunk_index=1,
            chunk_count=3,
            target_block_ids=["B005", "B006", "B007"],
            overlap_block_ids=["B003", "B004"],
            estimated_tokens=5800,
        )
        assert window.overlap_block_ids == ["B003", "B004"]
        assert window.estimated_tokens == 5800

    def test_rejects_extra_fields(self) -> None:
        with pytest.raises(ValidationError):
            PromptChunkWindow(
                window_id="w0",
                chunk_index=0,
                chunk_count=1,
                target_block_ids=["B001"],
                estimated_tokens=100,
                surprise_field="bad",
            )


class TestPromptPacketArtifact:
    def test_actors_packet(self) -> None:
        pkt = PromptPacketArtifact(
            packet_id="pkt_actors_w0",
            packet_family="actors",
            chunk_mode="single_pass",
            window_id="w0",
            prefix_path="prompt/packets/pkt_actors_w0/prefix.md",
            body_path="prompt/packets/pkt_actors_w0/body.md",
            rendered_path="prompt/packets/pkt_actors_w0/rendered.md",
            evidence_ids=["EV001", "EV002"],
        )
        assert pkt.packet_family == "actors"
        assert pkt.actor_roster_source_path is None

    def test_events_packet_with_roster(self) -> None:
        pkt = PromptPacketArtifact(
            packet_id="pkt_events_w0",
            packet_family="events",
            chunk_mode="chunked",
            window_id="w0",
            prefix_path="prompt/packets/pkt_events_w0/prefix.md",
            body_path="prompt/packets/pkt_events_w0/body.md",
            rendered_path="prompt/packets/pkt_events_w0/rendered.md",
            actor_roster_source_path="extract/actors_raw.json",
        )
        assert pkt.packet_family == "events"
        assert pkt.actor_roster_source_path == "extract/actors_raw.json"

    def test_rejects_invalid_family(self) -> None:
        with pytest.raises(ValidationError):
            PromptPacketArtifact(
                packet_id="bad",
                packet_family="unknown_family",
                chunk_mode="single_pass",
                window_id="w0",
                prefix_path="x",
                body_path="y",
                rendered_path="z",
            )

    def test_rejects_invalid_chunk_mode(self) -> None:
        with pytest.raises(ValidationError):
            PromptPacketArtifact(
                packet_id="bad",
                packet_family="actors",
                chunk_mode="triple_pass",
                window_id="w0",
                prefix_path="x",
                body_path="y",
                rendered_path="z",
            )


class TestPromptPacketManifest:
    def test_valid_manifest_with_packets(self) -> None:
        manifest = PromptPacketManifest(
            run_id="test-run-001",
            deal_slug="stec",
            source_accession_number="0001193125-13-123456",
            packets=[
                PromptPacketArtifact(
                    packet_id="pkt_actors_w0",
                    packet_family="actors",
                    chunk_mode="single_pass",
                    window_id="w0",
                    prefix_path="prompt/packets/pkt_actors_w0/prefix.md",
                    body_path="prompt/packets/pkt_actors_w0/body.md",
                    rendered_path="prompt/packets/pkt_actors_w0/rendered.md",
                ),
            ],
            asset_files=["prompt/assets/actor_taxonomy.md"],
            notes=["Generated by compose-prompts"],
        )
        assert manifest.artifact_type == "prompt_packet_manifest"
        assert manifest.deal_slug == "stec"
        assert len(manifest.packets) == 1
        assert manifest.packets[0].packet_family == "actors"

    def test_empty_manifest(self) -> None:
        manifest = PromptPacketManifest(
            run_id="test-run-002",
            deal_slug="imprivata",
        )
        assert manifest.packets == []
        assert manifest.asset_files == []
        assert manifest.notes == []

    def test_rejects_extra_fields(self) -> None:
        with pytest.raises(ValidationError):
            PromptPacketManifest(
                run_id="test-run-003",
                deal_slug="stec",
                extra_bad_field="nope",
            )

    def test_manifest_round_trips_through_json(self) -> None:
        manifest = PromptPacketManifest(
            run_id="rt-001",
            deal_slug="imprivata",
            source_accession_number="0001193125-16-696911",
            packets=[
                PromptPacketArtifact(
                    packet_id="pkt_actors_w0",
                    packet_family="actors",
                    chunk_mode="single_pass",
                    window_id="w0",
                    prefix_path="prompt/packets/pkt_actors_w0/prefix.md",
                    body_path="prompt/packets/pkt_actors_w0/body.md",
                    rendered_path="prompt/packets/pkt_actors_w0/rendered.md",
                    evidence_ids=["EV001"],
                ),
                PromptPacketArtifact(
                    packet_id="pkt_events_w0",
                    packet_family="events",
                    chunk_mode="chunked",
                    window_id="w0",
                    prefix_path="prompt/packets/pkt_events_w0/prefix.md",
                    body_path="prompt/packets/pkt_events_w0/body.md",
                    rendered_path="prompt/packets/pkt_events_w0/rendered.md",
                    actor_roster_source_path="extract/actors_raw.json",
                ),
            ],
            notes=["test round trip"],
        )
        json_str = manifest.model_dump_json()
        reloaded = PromptPacketManifest.model_validate_json(json_str)
        assert reloaded.deal_slug == "imprivata"
        assert len(reloaded.packets) == 2
        assert reloaded.packets[0].packet_family == "actors"
        assert reloaded.packets[1].packet_family == "events"
        assert reloaded.packets[1].actor_roster_source_path == "extract/actors_raw.json"

    def test_manifest_inherits_artifact_envelope_fields(self) -> None:
        manifest = PromptPacketManifest(
            run_id="env-001",
            deal_slug="stec",
        )
        assert manifest.schema_version is not None
        assert manifest.pipeline_version is not None
        assert manifest.created_at is not None
        assert manifest.artifact_type == "prompt_packet_manifest"
