"""Ordering constants for live analyst-export rows."""

EVENT_TYPE_PRIORITY = {
    "target_sale": 10,
    "target_sale_public": 11,
    "bidder_sale": 12,
    "bidder_interest": 13,
    "activist_sale": 14,
    "sale_press_release": 15,
    "bid_press_release": 16,
    "ib_retention": 20,
    "ib_terminated": 21,
    "nda": 30,
    "nda_amendment": 31,
    "standstill": 32,
    "exclusivity": 33,
    "clean_team": 34,
    "proposal": 40,
    "drop": 50,
    "final_round_inf_ann": 60,
    "final_round_inf": 61,
    "final_round_ann": 62,
    "final_round": 63,
    "final_round_ext_ann": 64,
    "final_round_ext": 65,
    "executed": 70,
    "terminated": 71,
    "restarted": 72,
}
