---
title: "Data Collection Instructions and Notes"
subtitle: "Informal Bids in Takeover Auctions"
author: "Alex Gorbenko"
date: 2026-03-03
format:
  pdf:
    documentclass: article
    fontsize: 11pt
    geometry: margin=1in
    number-sections: true
    colorlinks: true
    header-includes: |
      \usepackage{booktabs}
      \usepackage{longtable}
      \usepackage{float}
      \floatplacement{table}{H}
---

# Alex's Email, March 3, 2026 {.unnumbered}

> Hi Austin,
>
> So, here are some details about the database.
>
> 1. I have uploaded data collection instructions in Dropbox. This is a heavily modified document that Chicago guys used to collect their data (in turn, their document was created with the help of Andrey and I).
>
>     a. Everything in black is instructions by Chicago guys. Everything in bold red are my additions.
>
>     b. deal_details spreadsheet in Dropbox is data collected by Chicago RAs using instructions by Chicago guys. deal_details_Alex_2026 spreadsheet differs in 9 deals, for which I collected missing data that we need for our project and also corrected numerous data collection mistakes. Everything in red in this spreadsheet are fields that are either missing or incorrect in deal_details. Specifically, the 9 deals are:
>
>         - Providence & Worcester (Excel line 6024)
>         - Medivation (Excel line 6060)
>         - Imprivata (Excel line 6076)
>         - Zep (Excel line 6385)
>         - Petsmart (Excel line 6408)
>         - Penford (Excel line 6461)
>         - Mac Gray (Excel line 6927)
>         - Saks (Excel line 6996)
>         - STec (Excel line 7144)
>
>         The reason I have selected deals from the middle of the database is because earlier deals are collected poorly. I have previously read additional three deals from the beginning of the database, and there are many edits to be done there. At some point, I will add those edits to the database as well.
>
>     c. The most important fields are (in the Excel file, I made unimportant columns "invisible"):
>
>         - **TargetName**
>         - **Acquirer**
>         - **DateAnnounced**
>         - **DateEffective**
>         - **URL:** gives a direct link to a document with the deal background that we can read
>         - **bidderID:** this is an unfortunate name that really just enumerates events in their historical order. It can be about a bidder making a formal or informal bid, signing an NDA, dropping out (or getting dropped out by the target), the IB signing an agreement, and so on. The original dataset enumerated events by using integer numbers from 1 to N. In my edited dataset, I added various new events, such as retention of an IB, who initiated a sale process, etc. and had to squeeze these events between existing ones, so my dataset has non-integer numbers (e.g., if an IB signed a confidentiality agreement between event 1 and 2 in the original dataset, I would give 1.5 to the event of IB retention)
>         - **bidder_type_note:** bidder type: strategic, financial, non-US, etc.
>         - **bid_value and bid_value_pershare:** normally, these are equal. I think bid_value was created because sometimes the bid is written in deal backgrounds not on a per share basis but for the entire company (e.g., 10 billion). Then, it has to be divided by the number of shares outstanding to get bid_value_pershare. The only relevant thing for us is bid_value_pershare.
>         - **bid_value_lower and bid_value_upper:** for informal bids, if an interval is submitted.
>         - **bid_type:** informal or formal
>         - **bid_date_rough and bid_date_precise:** sometimes, an informal bid will be submitted, e.g., "in mid-February 20XX". I guess then there is no precise date but a rough date would be 2/15/20XX (note that all dates are in MM/DD/YYYY U.S. format!!). In my edited 9 deals, I did not bother with this distinction and simply edited bid_date_rough. We want to know the sequence of events but not necessarily the exact date.
>         - **bid_note:** please see the instructions. This describes the event on a given date, such as bid (NA), NDA, final bidding round announcement, final bidding round completion, retention of an IB, bidders dropping out or being dropped out, who initiated the deal process, etc, etc.
>         - **all_cash:** self-explanatory, 1 if a cash deal
>         - **cshoc:** this is a COMPUSTAT field with the number of shares outstanding, I think (to be verified)
>         - **comments_1, comments_2, comments_3:** I left some extensive comments about some bidders, bids, the sale process, and legal counsel there; some of these comments (definitely legal counsel) we should probably use.
>         - Again, everything in red in my dataset (for 9 deals) are fields that are either missing or incorrect in the original dataset.
>
> 2. Once you have read data collection instructions, I think it would be useful for you to read the 9 deal backgrounds that I read. First, it is useful for you to understand how M&A deals are conducted in practice, and how lawyers record various pieces of information (and how inconsistent they are across deals). Second, it would be useful for you to understand why I collected / corrected Chicago guys' information the way I did. This will allow us to fine-tune collection instructions in order to eventually feed them to an AI.
>
> 3. I think ideally it would also be useful for you to read another 5-6 deal backgrounds that I have not corrected yet, and manually correct the original dataset by Chicago guys. This detail-oriented reading will make you think about what else can be missing that we can later feed to the AI.
>
> I am sure I am probably missing something important... too many things to keep track of with these data. We can discuss this in greater detail (including the 9 deals + deals that you will have read on your own by then) perhaps next Thursday, March 12?
>
> Best,
>
> Alex

\newpage

# Goal

Collect detailed bidding data on corporate takeover auctions from deal backgrounds filed with the SEC via filings DEFM14A, PREM14A, SC-TOT, S4.

# Necessary Steps

1. Identify a transaction as an auction

    - Criterion: Multiple bidders have signed/executed confidentiality agreements

    - Financial and legal advisors to a deal also sign confidentiality agreements. Those instances are to be ignored for the classification purpose.

      ::: {.callout-note title="Alex's addition"}
      We collect these too. Financial advisors sign agreements around the start of a deal process. Legal advisors are often retained for a long time, so agreements have likely been signed much before the deal process starts -- there is no need to collect the date but the name of a legal advisor should be collected.
      :::

    - Sometimes backgrounds describe earlier attempts for a takeover if it is related. Ignore any confidentiality agreements from such a stale process.

2. Collect detailed bidding data

    - See detailed instructions below

3. Collect data on two types of press releases

    - There is typically a press release when the takeover is announced.

    - Sometimes the target company will put out a press release stating that they engage in a process to find potential buyers

    - Collect such information as "Press Release" in the "Bid Note" Column and the respective date in the "Date" Column. No other entries are made for this type of takeover event.

# Bidding Data Collection Instructions

## General

The deal backgrounds are chronological and dated description of the entire takeover process from the target's point of view.

## Start of the Sale Process

::: {.callout-note title="Alex's addition"}
Collect information on the party/parties responsible for the start of the sale process. It is probably best to return to this section once the rest of the instructions has been read for more clarity on the following.

This can get complicated. In some instances, the target is approached by a bidder with a bid. In some other instances, its board of directors decides to sell a company. It can also be that the board decides to sell but is approached by a bidder before they make any moves. Finally, it can be that the board is pressured by an activist investor.

Record the following information:

- **Bidder:** Only if the bidder approached the target; see @sec-nda-bidders, 'Bidder' for detail
- **Bidder Type:** Only if the bidder approached the target; see @sec-nda-bidders, 'Bidder Type' for detail
- **Bid:** Leave blank
- **Bid Note:** The description of what happened during the start of the sale process can take several lines. Use separate lines to record:

    - Record 'Target Sale' if there is a meeting of the board of directors in which a sale of the target was agreed upon. Record 'Target Sale Public' if public sale announcement was agreed upon. In this case, another line in the spreadsheet should contain the announcement date and 'Sale Press Release' in Bid Note [please see PetSmart Inc. as the example of such a deal in the spreadsheet]
    - Record 'Bidder Sale' if there is a bid from a bidder that triggers a sale process. If this bid is made public, another line in the spreadsheet should contain the announcement date and 'Bid Press Release' in Bid Note [please see Medivation Inc. as the example of such a deal in the spreadsheet]
    - Record both 'Target Sale' and 'Bidder Sale' in separate lines in the spreadsheet if the target decided to sell itself, but a bidder approached it with a bid before the target starts the process
    - Record 'Bidder Interest' if there is only bidder interest (eg discussions about a potential sale with the target's CEO) but no bid
    - Record, in a separate line in the spreadsheet, 'Activist Sale' if an activist is pressuring the target to sell itself. Normally this happens before 'Target Sale'.

- **Date:** Record the date of each event leading to the start of the process.
:::

### Spreadsheet Examples for Start of Sale Process

**PetSmart Inc.:** An activist announced a 9.9% stake and started pushing for a sale on 7/3/2014. The target decided to sell itself on 8/13/2014 with a public announcement. The announcement was made on 8/19/2014. These three events are three separate lines in the spreadsheet.

[Screenshot from spreadsheet: PetSmart example -- see original .docx]

**Medivation Inc.:** Sanofi made a bid on 4/13/2016. It was publicly announced (and next day rejected) on 4/28/2016. At this point, the target was viewed as 'for sale', hired an investment bank, and was approached by other parties.

[Screenshot from spreadsheet: Medivation example -- see original .docx]

**Imprivata Inc.:** 'Bidder Interest' can be followed by 'Bidder Sale'.

[Screenshot from spreadsheet: Imprivata example -- see original .docx]

## Investment Bank Retention

::: {.callout-note title="Alex's addition"}
Collect information on the investment bank engaged by the target.

May be described as an investment bank, investment banking firm, financial advisor, or something similar. Most of the time, there will be only one advisor, but sometimes there are several at once (in particular in large deals). In this case, there should be a primary advisor whom we should record. Otherwise, record all.

Record the following information. (It is probably best to return to this section once the rest of the instructions has been read for more clarity on the following.)

- **Bidder:** Name of _investment bank_
- **Bidder Type:** Leave blank
- **Bid:** Leave blank
- **Bid Note:** Record 'IB'
- **Date:** Record the date of the event in mm/dd/yy format
:::

## Confidentiality Agreements (NDAs) {#sec-nda-bidders}

Collect information on every bidder that signed a confidentiality agreement.

- Only focus on bidders that have signed or executed a confidentiality agreement, if a confidentiality agreement was sent but not returned or signed, ignore.

- First time a bidder with a signed confidentiality agreement is mentioned record the following columns:

| Field | Instructions |
|:------|:-------------|
| Bidder | Name of bidder. Only winning bidder name is disclosed; sometimes winning bidder is referred to as 'parent'. Losing bidders are usually referred to as 'Party A' or 'Bidder B', etc. There are bidders with confidentiality agreements that are not named; for such instances, name them as a1, a2, etc. If later they get named update the name accordingly. Note, there usually are instances when management reports to the board about the progress of the takeover. This often provides a summary of how many NDAs have been signed. Use this information to double check the collected information. |
| Bidder Type | Record the bidder type, i.e., strategic vs financial, also record status as public vs private and non-US if information is available. Sometimes financial bidders are referred to as: "private equity (funds)" or "financial fund". If a bidder has a CEO who engages in strategic talks with target, this is most likely a strategic bidder. Financial bidders however also engage in "strategic" talks. So the operative word is "Chief Executive". Strategic bidders: record an **S**. Financial bidders: record an **F**. If non-US: record "non-US S" or "non-US F". If public or private: "public S" or "public F". If all three information is given: record for example "non-US public S". |
| Bid | *(leave blank)* |
| Bid Note | Record "NDA" |
| Date | Record the date of the event in mm/dd/yy format |

: NDA recording fields {tbl-colwidths="[15,85]"}

## Submitted Bids

Collect information on every submitted bid.

- Only collect bids to acquire the entire company. Sometimes there will be bidders that only want to acquire a segment, or a percentage of the company, or a particular project. Don't record the information for those bids.

- For every bid to acquire the entire company, record:

| Field | Instructions |
|:------|:-------------|
| Bidder | Name of bidder as recorded when they signed the NDA |
| Bidder Type | Leave blank |
| Bid | Record amount of bid per share: Record the dollar number per share. If specified as a range: record the range as, e.g., 7.5-8. If it is only specified that six bidders made offers in the range between X and Y and there is no individual bid information for a bidder of that group record the indicated range as bid, i.e., X-Y. |
| Bid Note | Record the type of bid: formal vs informal. This requires some subjective judgement. Informal bid is often called an "informal indication of interest"; any bid expressed as a range is also to be classified as informal bid. Record a formal bid if the company announced a final round of bidding that only a subset of bidders is invited to (see example excerpt at the end). Record a formal bid if the bidder also submits/returns a draft or the marked-up copy of a merger agreement. |
| Date | Record the date of the event in mm/dd/yy format |

: Bid recording fields {tbl-colwidths="[15,85]"}

## Bidder Dropouts

Collect data on bidders dropping out.

- Record the following information if a bidder informs the company that they are dropping out of the process or are no longer interested in pursuing the transaction.

- Note that sometimes bidders re-enter the bidding; in those cases still record the earlier dropout notice.

- Record the following information:

| Field | Instructions |
|:------|:-------------|
| Bidder | Name of bidder as recorded when they signed the NDA |
| Bidder Type | Leave blank |
| Bid | Leave blank |
| Bid Note | Record the type of dropout: Record 'Drop', if only informed of the drop-out. Record 'DropBelowM' if bidder informs them that their valuation is lower than the company's market value. |
| Date | Record the date of the event in mm/dd/yy format |

: Dropout recording fields (Chicago instructions) {tbl-colwidths="[15,85]"}

::: {.callout-note title="Alex's addition — additional dropout types"}
In addition to the dropout types above, also record:

- Record **'DropBelowInf'** if bidder informs them that their valuation is lower than the earlier bid in the informal round
- Record **'DropAtInf'** if bidder informs that their valuation is at the earlier bid in the informal round
- Record **'DropTarget'** if target does not invite the bidder to the final round
:::

## Final Round Announcements and Deadlines

::: {.callout-note title="Alex's addition"}
Collect data on the target announcing the final round and its deadline.

Note that this information should precede information in the Bidder Dropouts section above, in which the target decides to drop some of the bidders ('DropTarget') who are insufficiently strong. It also should precede information in which some of the bidders decide to drop out around the target's announcement of the final round ('Drop' or 'DropBelowM'). (Some of these bidders were likely informed by the target that their bid was inadequate and decided to drop out on their own.)

Record the following information:

- **Bidder:** Leave blank
- **Bidder Type:** Leave blank
- **Bid:** Leave blank
- **Bid Note:**
    - Record 'Final Round Ann' if this is the announcement of the final round
    - Record 'Final Round' if this is the deadline to submit bids in the final round
    - If there is also a final round of informal bids, record 'Final Round Inf Ann' and 'Final Round Inf' as described above
    - If the final round is extended, record 'Final Round Ext Ann' and 'Final Round Ext' as described above
- **Date:** Record the date of the event in mm/dd/yy format
:::

## Executing the Merger Agreement

::: {.callout-note title="Alex's addition"}
Collect date of executing the merger agreement.

Record the following information:

- **Bidder:** Name of bidder as recorded when they signed the NDA
- **Bidder Type:** Leave blank
- **Bid Note:** Record 'Executed'
- **Date:** Record the date of the event in mm/dd/yy format
:::

## Termination and Restart of Earlier Sale Processes

::: {.callout-note title="Alex's addition"}
Sometimes, a company that wants to sell itself has several attempts at it. Often, earlier attempts are also recorded in the deal background. It can be useful to record these attempts, as well as when these earlier sale processes have been terminated.

Record the following information:

- **Bidder:**
    - Leave blank if Bid Note = 'Terminated'
    - Name of bidder as recorded when they signed the NDA if Bid Note = 'Restarted'
- **Bidder Type:**
    - Leave blank if Bid Note = 'Terminated'
    - As described in the NDA section if Bid Note = 'Restarted'
- **Bid Note:**
    - Record 'Terminated' if the deal was terminated by the target due to the lack of interest [as an example, see Zep Inc in the database]
    - Record 'Restarted' if the sale process (by the same target) was restarted later on (it is possible that it will have an entirely different set of bidders)
- **Date:** Record the date of the event in mm/dd/yy format
:::

# Example Excerpts

> *"Beginning on December 19, 2012, representatives of BofA Merrill Lynch and Deutsche Bank, on behalf of the Company, sent final round process letters to OTPP, Bidder A and Bidder B, which process letters requested bidders to submit a final binding offer to acquire 100% of the equity of the Company, together with a markup of the agreement and plan of amalgamation that such bidder would be prepared to execute immediately, by January 10, 2013."*

Record all bids of OTPP, A, and B after that date as **formal**.

> *"On August 28, 2012, Party O submitted a revised proposal of $55 million for the Company's business in the United Kingdom and Europe."*

Don't record bid because only bid for part of the company.
